import java.time.Instant
import java.util.Properties
import org.gradle.api.tasks.SourceSetContainer

plugins { alias(libs.plugins.shadow) }

tasks.build { dependsOn("shadowJar") }

val generatedBuildInfoDir = layout.buildDirectory.dir("generated/resources/runic-build-info")

fun git(vararg args: String): String? {
    return try {
        providers
            .exec { commandLine("git", *args) }
            .standardOutput
            .asText
            .get()
            .trim()
            .ifEmpty { null }
    } catch (_: Exception) {
        null
    }
}

fun resolveBuildValue(
    propertyName: String,
    envName: String,
    fallback: () -> String? = { null },
): String {
    val propertyValue = providers.gradleProperty(propertyName).orNull?.trim()
    if (!propertyValue.isNullOrEmpty()) {
        return propertyValue
    }

    val envValue = providers.environmentVariable(envName).orNull?.trim()
    if (!envValue.isNullOrEmpty()) {
        return envValue
    }

    return fallback()?.trim()?.takeIf { it.isNotEmpty() } ?: "unknown"
}

val generateRunicBuildInfo by
    tasks.registering {
        val outputFile = generatedBuildInfoDir.map { it.file("runic-build-info.properties") }
        outputs.file(outputFile)

        doLast {
            val commitSha =
                resolveBuildValue("runicBuildSha", "RUNIC_GIT_SHA") { git("rev-parse", "HEAD") }
            val branch =
                resolveBuildValue("runicBuildBranch", "RUNIC_GIT_BRANCH") {
                    git("rev-parse", "--abbrev-ref", "HEAD")
                }
            val commitMessage =
                resolveBuildValue("runicBuildMessage", "RUNIC_GIT_MESSAGE") {
                    git("log", "-1", "--pretty=%s")
                }
            val buildId =
                resolveBuildValue("runicBuildId", "RUNIC_BUILD_ID") {
                    providers.environmentVariable("GITHUB_RUN_ID").orNull
                }
            val buildSource =
                if (providers.environmentVariable("GITHUB_ACTIONS").orNull == "true")
                    "github-actions"
                else "local"
            val pluginVersion =
                project.version.toString().takeUnless { it == "unspecified" }
                    ?: rootProject.version.toString()

            val properties = Properties()
            properties["branch"] = branch
            properties["commitSha"] = commitSha
            properties["commitShortSha"] = commitSha.take(7)
            properties["commitMessage"] = commitMessage
            properties["buildId"] = buildId
            properties["buildSource"] = buildSource
            properties["builtAtUtc"] = Instant.now().toString()
            properties["pluginVersion"] = pluginVersion

            val file = outputFile.get().asFile
            file.parentFile.mkdirs()
            file.outputStream().use { stream ->
                properties.store(stream, "Generated by :plugin:generateRunicBuildInfo")
            }
        }
    }

dependencies {
    implementation(project(":data"))
    implementation(project(":common"))
    implementation(project(":gameplay"))
    implementation(project(":items"))
}

tasks.shadowJar {
    archiveBaseName.set("game-plugin")
    mergeServiceFiles() // Necessary because of something to do with gRPC managed channels
    relocate("com.google.protobuf", "shadow.com.google.protobuf")
    relocate("com.fasterxml.jackson", "shadow.com.fasterxml.jackson")
    relocate("co.aikar.commands", "game.com.aikar.commands")
    relocate("co.aikar.locales", "game.aikar.locales")
}

the<SourceSetContainer>()["main"].resources.srcDir(generatedBuildInfoDir)

tasks.processResources { dependsOn(generateRunicBuildInfo) }
